USE projetoW;

CREATE TABLE IF NOT EXISTS USUARIO(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(150),
    SENHA VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS CLIENTE(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(150),
    CPF VARCHAR(150),
    ENDERECO VARCHAR(150),
    EMAIL VARCHAR(150),
    TELEFONE VARCHAR(25)
);

CREATE TABLE IF NOT EXISTS VEICULO(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MARCA VARCHAR(150),
    MODELO VARCHAR(150),
    ANO INT,
    DESCRICAO TEXT,
    PLACA VARCHAR(25),
    CHASSI VARCHAR(150),
    QUANTIDADE INT,
    PRECO DOUBLE
);

CREATE TABLE IF NOT EXISTS ESTOQUE(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VEICULO INT,
    QUANTIDADE INT,
    FOREIGN KEY(VEICULO) REFERENCES VEICULO(ID)
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(150),
    SALARIO DOUBLE,
    ENDERECO VARCHAR(150),
    CPF VARCHAR(25)
);

CREATE TABLE IF NOT EXISTS BONIFICACAO(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VALOR DOUBLE
);

CREATE TABLE IF NOT EXISTS VENDA(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FUNCIONARIO INT,
    CLIENTE INT,
    VEICULO INT,
    DATA DATETIME,
    VALOR DOUBLE,
    FOREIGN KEY(FUNCIONARIO) REFERENCES FUNCIONARIO(ID),
    FOREIGN KEY(CLIENTE) REFERENCES CLIENTE(ID),
    FOREIGN KEY(VEICULO) REFERENCES VEICULO(ID)
);