/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wpm.Apresentacao;

import br.com.wpm.Dados.ClienteDAO;
import br.com.wpm.Dados.VeiculoDAO;
import br.com.wpm.Entidade.Veiculo;
import br.com.wpm.Negocio.VeiculoBO;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author wesley
 */
public class ListaVeiculoForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaVeiculoForm
     */
    private Veiculo veiculo;

    public ListaVeiculoForm() {
        initComponents();
        ConfigurarTblVeiculo();
        bloquear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVeiculo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edtMarca = new javax.swing.JTextField();
        edtAno = new javax.swing.JTextField();
        edtModelo = new javax.swing.JTextField();
        edtPlaca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edtChassi = new javax.swing.JTextField();
        edtQtd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        edtPreco = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        edtDescricao = new javax.swing.JTextArea();
        btnAlterar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tblVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVeiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVeiculo);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Marca:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Modelo:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Descrição:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("Ano:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setText("Placa:");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("Chassi:");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setText("Qtd:");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setText("Preço:");

        edtDescricao.setColumns(20);
        edtDescricao.setRows(5);
        jScrollPane2.setViewportView(edtDescricao);

        btnAlterar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnApagar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtPlaca))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtModelo)
                            .addComponent(edtChassi)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 9, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(edtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(edtChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(edtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(edtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar)
                    .addComponent(btnApagar)
                    .addComponent(btnCancelar))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try {
            veiculo.setMarca(edtMarca.getText().trim());
            veiculo.setModelo(edtModelo.getText().trim());
            veiculo.setAno(Integer.parseInt(edtAno.getText().trim()));
            veiculo.setDescricao(edtDescricao.getText().trim());
            veiculo.setPlaca(edtPlaca.getText().trim());
            veiculo.setChassi(edtChassi.getText().trim());
            veiculo.setQuantidade(Integer.parseInt(edtQtd.getText().trim()));
            veiculo.setPreco(Double.parseDouble(edtPreco.getText().trim()));
            if (veiculo.getMarca().isEmpty() || veiculo.getPlaca().isEmpty() || veiculo.getDescricao().isEmpty() || veiculo.getPlaca().isEmpty()
                    || veiculo.getChassi().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha Todos os Campos!", "Campo Vazio!", JOptionPane.WARNING_MESSAGE);
            } else {
                int verificacao = JOptionPane.showConfirmDialog(this, "Tem Certeza que Deseja Alterar?", "Confirmação", JOptionPane.YES_NO_OPTION);
                if (verificacao == JOptionPane.YES_OPTION) {
                    VeiculoBO veiculoBO = new VeiculoBO();
                    veiculoBO.editar(veiculo);
                    JOptionPane.showMessageDialog(this, "Alteração Realizada com Sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
                }
                bloquear();
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Valores Inválidos!", "Campo Inválido!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void tblVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVeiculoMouseClicked
        int cod = tblVeiculo.getSelectedRow();
        VeiculoDAO veiculoDAO = new VeiculoDAO();
        veiculo = veiculoDAO.listaVeiculo().get(cod);
        edtMarca.setText(veiculo.getMarca());
        edtModelo.setText(veiculo.getModelo());
        edtAno.setText(Integer.toString(veiculo.getAno()));
        edtPlaca.setText(veiculo.getPlaca());
        edtChassi.setText(veiculo.getChassi());
        edtDescricao.setText(veiculo.getDescricao());
        edtQtd.setText(Integer.toString(veiculo.getQuantidade()));
        edtPreco.setText(Double.toString(veiculo.getPreco()));
        edtMarca.setEnabled(true);
        edtModelo.setEnabled(true);
        edtAno.setEnabled(true);
        edtPlaca.setEnabled(true);
        edtChassi.setEnabled(true);
        edtDescricao.setEnabled(true);
        edtQtd.setEnabled(true);
        edtPreco.setEnabled(true);
    }//GEN-LAST:event_tblVeiculoMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        bloquear();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        try {
            int verificacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja apagar?", "Confirmacação", JOptionPane.YES_NO_OPTION);
            if (verificacao == JOptionPane.YES_OPTION) {
                VeiculoBO veiculoBO = new VeiculoBO();
                veiculoBO.apagar(veiculo.getId());
                JOptionPane.showMessageDialog(this, "Remoção Realizada com Sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                bloquear();
            } else {
                bloquear();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Dados Inacecivel!", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnApagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTextField edtAno;
    private javax.swing.JTextField edtChassi;
    private javax.swing.JTextArea edtDescricao;
    private javax.swing.JTextField edtMarca;
    private javax.swing.JTextField edtModelo;
    private javax.swing.JTextField edtPlaca;
    private javax.swing.JTextField edtPreco;
    private javax.swing.JTextField edtQtd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblVeiculo;
    // End of variables declaration//GEN-END:variables

    private void ConfigurarTblVeiculo() {
        TableVeiculoModel model = new TableVeiculoModel(new VeiculoDAO().listaVeiculo());
        tblVeiculo.setModel(model);
    }

    private class TableVeiculoModel extends AbstractTableModel {

        private List<Veiculo> lista;

        public TableVeiculoModel(List<Veiculo> lista) {
            this.lista = lista;
        }

        @Override
        public int getRowCount() {
            return lista.size();
        }

        @Override
        public int getColumnCount() {
            return 8;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Veiculo veiculo = lista.get(rowIndex);
            if (columnIndex == 0) {
                return veiculo.getMarca();
            } else if (columnIndex == 1) {
                return veiculo.getModelo();
            } else if (columnIndex == 2) {
                return veiculo.getAno();
            } else if (columnIndex == 3) {
                return veiculo.getDescricao();
            } else if (columnIndex == 4) {
                return veiculo.getPlaca();
            } else if (columnIndex == 5) {
                return veiculo.getChassi();
            } else if (columnIndex == 6) {
                return veiculo.getQuantidade();
            } else if (columnIndex == 7) {
                return veiculo.getPreco();
            }
            return null;
        }

        @Override
        public String getColumnName(int column) {
            if (column == 0) {
                return "Marca";
            } else if (column == 1) {
                return "Modelo";
            } else if (column == 2) {
                return "Ano";
            } else if (column == 3) {
                return "Descrição";
            } else if (column == 4) {
                return "Placa";
            } else if (column == 5) {
                return "Chassi";
            } else if (column == 6) {
                return "Quantidade";
            } else if (column == 7) {
                return "Preço";
            }
            return null;
        }

    }

    public void bloquear() {
        edtMarca.setText("");
        edtModelo.setText("");
        edtAno.setText("");
        edtPlaca.setText("");
        edtChassi.setText("");
        edtDescricao.setText("");
        edtQtd.setText("");
        edtPreco.setText("");
        edtMarca.setEnabled(false);
        edtModelo.setEnabled(false);
        edtAno.setEnabled(false);
        edtPlaca.setEnabled(false);
        edtChassi.setEnabled(false);
        edtDescricao.setEnabled(false);
        edtQtd.setEnabled(false);
        edtPreco.setEnabled(false);
        ConfigurarTblVeiculo();
    }
}
