/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wpm.Apresentacao;

import br.com.wpm.Dados.ClienteDAO;
import br.com.wpm.Dados.FuncionarioDAO;
import br.com.wpm.Entidade.Funcionario;
import br.com.wpm.Excecao.CpfDuplicado;
import br.com.wpm.Excecao.NomeDuplicado;
import br.com.wpm.Negocio.FuncionarioBO;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author wesley
 */
public class ListaFuncionarioForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaFuncionario
     */
    private Funcionario funcionario;

    public ListaFuncionarioForm() {
        initComponents();
        ConfigurarTblFuncionario();
        bloquear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        edtCpf = new javax.swing.JFormattedTextField();
        edtEndereco = new javax.swing.JTextField();
        edtSalario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        btnAlterar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Cpf:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Salario");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("Endereço:");

        try {
            edtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tblFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFuncionario);

        btnAlterar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnApagar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtEndereco))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtSalario))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(edtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnApagar)
                    .addComponent(btnCancelar))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        bloquear();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try {
            funcionario.setNome(edtNome.getText().trim());
            funcionario.setCpf(edtCpf.getText().trim());
            funcionario.setEndereco(edtEndereco.getText().trim());
            funcionario.setSalario(Double.parseDouble(edtSalario.getText().trim()));
            if (funcionario.getNome().isEmpty() || (funcionario.getCpf().length() == 9) || funcionario.getEndereco().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha Todos os Campo!", "Campo Vazio!", JOptionPane.WARNING_MESSAGE);
            } else {
                FuncionarioBO funcionarioBO = new FuncionarioBO();
                int verificacao = JOptionPane.showConfirmDialog(this, "Tem Certeza que Deseja Alterar?", "Confirmação", JOptionPane.YES_NO_OPTION);
                if (verificacao == JOptionPane.YES_OPTION) {
                    funcionarioBO.editar(funcionario);
                    JOptionPane.showMessageDialog(this, "Alteração Realizada com Sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    bloquear();
                    ConfigurarTblFuncionario();
                } else {
                    bloquear();
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Valores Inválidos", "Campo Inválido!", JOptionPane.WARNING_MESSAGE);
        } catch (NomeDuplicado e) {
            JOptionPane.showMessageDialog(this, "Nome Inválido!", "Campo Inválido!", JOptionPane.WARNING_MESSAGE);
        } catch (CpfDuplicado e) {
            JOptionPane.showMessageDialog(this, "Cpf Inválidos", "Campo Inválido!", JOptionPane.WARNING_MESSAGE);
        } catch (HeadlessException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void tblFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFuncionarioMouseClicked
        int cod = tblFuncionario.getSelectedRow();
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        funcionario = funcionarioDAO.listaFuncionario().get(cod);
        edtNome.setText(funcionario.getNome());
        edtCpf.setText(funcionario.getCpf());
        edtEndereco.setText(funcionario.getEndereco());
        edtSalario.setText(Double.toString(funcionario.getSalario()));
        edtNome.setEnabled(true);
        edtCpf.setEnabled(true);
        edtEndereco.setEnabled(true);;
        edtSalario.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnApagar.setEnabled(true);
        btnCancelar.setEnabled(true);
    }//GEN-LAST:event_tblFuncionarioMouseClicked

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        try {
            int verificacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja apagar?", "Confirmacação", JOptionPane.YES_NO_OPTION);
            if (verificacao == JOptionPane.YES_OPTION) {
                FuncionarioBO funcionarioBO = new FuncionarioBO();
                funcionarioBO.apagar(funcionario.getId());
                JOptionPane.showMessageDialog(this, "Remoção Realizada com Sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                bloquear();
            } else {
                bloquear();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Dados Inacecivel!", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnApagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JFormattedTextField edtCpf;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtSalario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFuncionario;
    // End of variables declaration//GEN-END:variables

    private void ConfigurarTblFuncionario() {
        TableFuncionarioModel model = new TableFuncionarioModel(new FuncionarioDAO().listaFuncionario());
        tblFuncionario.setModel(model);

    }

    private class TableFuncionarioModel extends AbstractTableModel {

        private List<Funcionario> lista;

        public TableFuncionarioModel(List<Funcionario> lista) {
            this.lista = lista;
        }

        @Override
        public int getRowCount() {
            return lista.size();
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Funcionario funcionario = lista.get(rowIndex);
            if (columnIndex == 0) {
                return funcionario.getNome();
            } else if (columnIndex == 1) {
                return funcionario.getCpf();
            } else if (columnIndex == 2) {
                return funcionario.getEndereco();
            } else if (columnIndex == 3) {
                return funcionario.getSalario();
            }
            return null;
        }

        @Override
        public String getColumnName(int column) {
            if (column == 0) {
                return "Nome";
            } else if (column == 1) {
                return "Cpf";
            } else if (column == 2) {
                return "Endereço";
            } else if (column == 3) {
                return "Salário";
            }
            return null;
        }
    }

    private void bloquear() {
        edtNome.setText("");
        edtCpf.setText("");
        edtEndereco.setText("");
        edtSalario.setText("");
        edtNome.setEnabled(false);
        edtCpf.setEnabled(false);
        edtEndereco.setEnabled(false);;
        edtSalario.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnApagar.setEnabled(false);
        btnCancelar.setEnabled(false);
        ConfigurarTblFuncionario();
    }
}
