/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wpm.Apresentacao;

import br.com.wpm.Dados.VendaDAO;
import br.com.wpm.Entidade.Venda;
import java.util.List;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author wesley
 */
public class ListaVendaForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaVendaForm
     */
    public ListaVendaForm() {
        initComponents();
        ConfigurarTblVeiculo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVenda = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tblVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVenda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVenda;
    // End of variables declaration//GEN-END:variables

    private void ConfigurarTblVeiculo() {
        TableVendaModel model = new TableVendaModel(new VendaDAO().listaVenda());
        tblVenda.setModel(model);
    }

    private class TableVendaModel extends AbstractTableModel {

        private List<Venda> lista;

        public TableVendaModel(List<Venda> lista) {
            this.lista = lista;
        }

        @Override
        public int getRowCount() {
            return lista.size();
        }

        @Override
        public int getColumnCount() {
            return 5;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Venda venda = lista.get(rowIndex);
            if (columnIndex == 0) {
                return venda.getFuncionario();
            } else if (columnIndex == 1) {
                return venda.getCliente();
            } else if (columnIndex == 2) {
                return venda.getVeiculo();
            } else if (columnIndex == 3) {
                return venda.getData();
            } else if (columnIndex == 4) {
                return venda.getValor();
            }
            return null;
        }

        @Override
        public String getColumnName(int column) {
            if (column == 0) {
                return "Funcionario";
            } else if (column == 1) {
                return "Cliente";
            } else if (column == 2) {
                return "Veiculo";
            } else if (column == 3) {
                return "Data";
            } else if (column == 4) {
                return "Valor";
            }
            return null;
        }

    }
}
