/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wpm.Apresentacao;

import br.com.wpm.Dados.ClienteDAO;
import br.com.wpm.Entidade.Cliente;
import br.com.wpm.Excecao.CpfDuplicado;
import br.com.wpm.Excecao.EmailDuplicado;
import br.com.wpm.Excecao.NomeDuplicado;
import br.com.wpm.Excecao.TelefoneDuplicado;
import br.com.wpm.Negocio.ClienteBO;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author wesley
 */
public class ListaClienteForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaClienteForm
     */
    private Cliente cliente;

    public ListaClienteForm() {
        initComponents();
        ConfigurarTblCliente();
        bloquear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        edtCpf = new javax.swing.JFormattedTextField();
        edtEndereco = new javax.swing.JTextField();
        edtEmail = new javax.swing.JTextField();
        edtTelefone = new javax.swing.JFormattedTextField();
        btnAlterar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCliente);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Cpf:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Endereço:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setText("Telefone:");

        try {
            edtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            edtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnAlterar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnApagar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edtNome)
                            .addComponent(edtEndereco)
                            .addComponent(edtTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtCpf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtEmail))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 44, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(edtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar)
                    .addComponent(btnApagar)
                    .addComponent(btnCancelar))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        int cod = tblCliente.getSelectedRow();
        ClienteDAO clienteDAO = new ClienteDAO();
        cliente = clienteDAO.listaCliente().get(cod);
        edtNome.setText(cliente.getNome());
        edtNome.setEnabled(true);
        edtCpf.setText(cliente.getCpf());
        edtCpf.setEnabled(true);
        edtEndereco.setText(cliente.getEndereco());
        edtEndereco.setEnabled(true);
        edtEmail.setText(cliente.getEmail());
        edtEmail.setEnabled(true);
        edtTelefone.setText(cliente.getTelefone());
        edtTelefone.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnApagar.setEnabled(true);
        btnCancelar.setEnabled(true);
    }//GEN-LAST:event_tblClienteMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        bloquear();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        cliente.setNome(edtNome.getText().trim());
        cliente.setCpf(edtCpf.getText().trim());
        cliente.setEndereco(edtEndereco.getText().trim());
        cliente.setEmail(edtEmail.getText().trim());
        cliente.setTelefone(edtTelefone.getText().trim());
        if (cliente.getNome().isEmpty() || (cliente.getCpf().length() == 9) || cliente.getEndereco().isEmpty() || cliente.getEmail().isEmpty()
                || (cliente.getTelefone().length() == 10)) {
            JOptionPane.showMessageDialog(this, "Preencha Todos os Campo!", "Campo Vazio!", JOptionPane.WARNING_MESSAGE);
        } else {
            ClienteBO clienteBO = new ClienteBO();
            int verificacao = JOptionPane.showConfirmDialog(this, "Tem Certeza que Deseja Alterar?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (verificacao == JOptionPane.YES_OPTION) {
                try {
                    clienteBO.editar(cliente);
                    JOptionPane.showMessageDialog(this, "Alteração Realizada com Sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    bloquear();
                    ConfigurarTblCliente();
                } catch (NomeDuplicado e) {
                    JOptionPane.showMessageDialog(this, "Nome Inválido!", "Erro Dados!", JOptionPane.WARNING_MESSAGE);
                } catch (CpfDuplicado e) {
                    JOptionPane.showMessageDialog(this, "Cpf Inválido!", "Erro Dados!", JOptionPane.WARNING_MESSAGE);
                } catch (EmailDuplicado e) {
                    JOptionPane.showMessageDialog(this, "Email Inválido!", "Erro Dados!", JOptionPane.WARNING_MESSAGE);
                } catch (TelefoneDuplicado e) {
                    JOptionPane.showMessageDialog(this, "Telefone Inválido!", "Erro Dados!", JOptionPane.WARNING_MESSAGE);
                } catch (HeadlessException e) {
                    e.printStackTrace();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            } else {
                bloquear();
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        try {
            int verificacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja apagar?", "Confirmacação", JOptionPane.YES_NO_OPTION);
            if (verificacao == JOptionPane.YES_OPTION) {
                ClienteDAO clienteDAO = new ClienteDAO();
                clienteDAO.apagar(cliente.getId());
                JOptionPane.showMessageDialog(this, "Remoção Realizada com Sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                bloquear();
            } else {
                bloquear();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Dados Inacecivel!", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnApagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JFormattedTextField edtCpf;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextField edtNome;
    private javax.swing.JFormattedTextField edtTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCliente;
    // End of variables declaration//GEN-END:variables

    private void ConfigurarTblCliente() {
        TableClienteModel model = new TableClienteModel(new ClienteDAO().listaCliente());
        tblCliente.setModel(model);

    }

    private class TableClienteModel extends AbstractTableModel {

        private List<Cliente> lista;

        public TableClienteModel(List<Cliente> lista) {
            this.lista = lista;
        }

        @Override
        public int getRowCount() {
            return lista.size();
        }

        @Override
        public int getColumnCount() {
            return 5;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Cliente cliente = lista.get(rowIndex);
            if (columnIndex == 0) {
                return cliente.getNome();
            } else if (columnIndex == 1) {
                return cliente.getCpf();
            } else if (columnIndex == 2) {
                return cliente.getEndereco();
            } else if (columnIndex == 3) {
                return cliente.getEmail();
            } else if (columnIndex == 4) {
                return cliente.getTelefone();
            }
            return null;
        }

        @Override
        public String getColumnName(int column) {
            if (column == 0) {
                return "Nome";
            } else if (column == 1) {
                return "Cpf";
            } else if (column == 2) {
                return "Endereço";
            } else if (column == 3) {
                return "Email";
            } else if (column == 4) {
                return "Telefone";
            }
            return null;
        }
    }

    private void bloquear() {
        edtNome.setText("");
        edtCpf.setText("");
        edtEmail.setText("");
        edtEndereco.setText("");
        edtTelefone.setText("");
        edtNome.setEnabled(false);
        edtCpf.setEnabled(false);
        edtEndereco.setEnabled(false);
        edtEmail.setEnabled(false);
        edtTelefone.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnApagar.setEnabled(false);
        btnCancelar.setEnabled(false);
        ConfigurarTblCliente();
    }
}
