/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wpm.Apresentacao;

import br.com.wpm.Dados.ClienteDAO;
import br.com.wpm.Dados.FuncionarioDAO;
import br.com.wpm.Dados.VeiculoDAO;
import br.com.wpm.Entidade.Cliente;
import br.com.wpm.Entidade.Funcionario;
import br.com.wpm.Entidade.Veiculo;
import br.com.wpm.Entidade.Venda;
import br.com.wpm.Negocio.VendaBO;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author wesley
 */
public class NovaVendaForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form NovaVenda
     */
    public NovaVendaForm() {
        initComponents();
        ConfigurarCmbFuncionario();
        ConfigurarCmbCliente();
        ConfigurarCmbVeiculo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbFuncionario = new javax.swing.JComboBox();
        cmbCliente = new javax.swing.JComboBox();
        cmbVeiculo = new javax.swing.JComboBox();
        btnCadastrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Funcionário:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Cliente:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("Veiculo:");

        btnCadastrar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbFuncionario, 0, 393, Short.MAX_VALUE)
                            .addComponent(cmbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbVeiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            Double valor;
            Venda venda = new Venda(((Funcionario) cmbFuncionario.getSelectedItem()), ((Cliente) cmbCliente.getSelectedItem()),
                    ((Veiculo) cmbVeiculo.getSelectedItem()));
            VendaBO vendaBO = new VendaBO();
            if (vendaBO.verificarDesconto(venda.getCliente().getId())) {
                Double desconto = Double.parseDouble(JOptionPane.showInputDialog(this, "Qual a porcentagem de Desconto?"));
                Double valorDescontado = ((Veiculo) cmbVeiculo.getSelectedItem()).getPreco() * (desconto / 100);
                valor = ((Veiculo) cmbVeiculo.getSelectedItem()).getPreco() - valorDescontado;
            } else {
                valor = ((Veiculo) cmbVeiculo.getSelectedItem()).getPreco();
            }
            Date date = new Date();
            java.sql.Date dataSql = new java.sql.Date(date.getTime());
            venda.setValor(valor);
            venda.setData(dataSql);
            if (((Veiculo) cmbVeiculo.getSelectedItem()).getQuantidade() > 0) {
                vendaBO.cadastrar(venda);
                JOptionPane.showMessageDialog(this, "Cadastro Realizado com Sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                ConfigurarCmbCliente();
                ConfigurarCmbFuncionario();
                ConfigurarCmbVeiculo();
            } else {
                JOptionPane.showMessageDialog(this, "Estoque Indisponivel!", "Dado Inválido!", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Valor Inválido!", "Dado Inválido!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox cmbCliente;
    private javax.swing.JComboBox cmbFuncionario;
    private javax.swing.JComboBox cmbVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private void ConfigurarCmbFuncionario() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) this.cmbFuncionario.getModel();
        model.removeAllElements();
        for (Funcionario funcionario : new FuncionarioDAO().listaFuncionario()) {
            model.addElement(funcionario);
        }
    }

    private void ConfigurarCmbCliente() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) this.cmbCliente.getModel();
        model.removeAllElements();
        for (Cliente cliente : new ClienteDAO().listaCliente()) {
            model.addElement(cliente);
        }
    }

    private void ConfigurarCmbVeiculo() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) this.cmbVeiculo.getModel();
        model.removeAllElements();
        for (Veiculo veiculo : new VeiculoDAO().listaVeiculo()) {
            model.addElement(veiculo);
        }
    }
}
