/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wpm.Apresentacao;

import br.com.wpm.Dados.FuncionarioDAO;
import br.com.wpm.Dados.VendaDAO;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author wesley
 */
public class TelaPrincipalForm extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalForm
     */
    public TelaPrincipalForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuNovoCliente = new javax.swing.JMenuItem();
        mnuListaCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuNovoVeiculo = new javax.swing.JMenuItem();
        mnuListaVeiculo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuNovoFuncionario = new javax.swing.JMenuItem();
        mnuListaFuncionario = new javax.swing.JMenuItem();
        mnuBonificacao = new javax.swing.JMenu();
        mnuNovaVenda = new javax.swing.JMenuItem();
        mnuListaVenda = new javax.swing.JMenuItem();
        btnBonificacao = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuRelatorioCompra = new javax.swing.JMenuItem();
        mnuFuncionarioPorVenda = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuGraficoMarca = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        jMenu1.setText("Cliente");

        mnuNovoCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnuNovoCliente.setText("Novo");
        mnuNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNovoClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mnuNovoCliente);

        mnuListaCliente.setText("Listar");
        mnuListaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListaClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mnuListaCliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Veiculo");

        mnuNovoVeiculo.setText("Novo");
        mnuNovoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNovoVeiculoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuNovoVeiculo);

        mnuListaVeiculo.setText("Listar");
        mnuListaVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListaVeiculoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuListaVeiculo);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Funcionario");

        mnuNovoFuncionario.setText("Novo");
        mnuNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNovoFuncionarioActionPerformed(evt);
            }
        });
        jMenu3.add(mnuNovoFuncionario);

        mnuListaFuncionario.setText("Listar");
        mnuListaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListaFuncionarioActionPerformed(evt);
            }
        });
        jMenu3.add(mnuListaFuncionario);

        jMenuBar1.add(jMenu3);

        mnuBonificacao.setText("Venda");

        mnuNovaVenda.setText("Realizar Venda");
        mnuNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNovaVendaActionPerformed(evt);
            }
        });
        mnuBonificacao.add(mnuNovaVenda);

        mnuListaVenda.setText("Listar");
        mnuListaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListaVendaActionPerformed(evt);
            }
        });
        mnuBonificacao.add(mnuListaVenda);

        btnBonificacao.setText("Bonificação");
        btnBonificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBonificacaoActionPerformed(evt);
            }
        });
        mnuBonificacao.add(btnBonificacao);

        jMenuBar1.add(mnuBonificacao);

        jMenu4.setText("Relatorios");

        mnuRelatorioCompra.setText("Compra");
        mnuRelatorioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRelatorioCompraActionPerformed(evt);
            }
        });
        jMenu4.add(mnuRelatorioCompra);

        mnuFuncionarioPorVenda.setText("Funcionário");
        mnuFuncionarioPorVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFuncionarioPorVendaActionPerformed(evt);
            }
        });
        jMenu4.add(mnuFuncionarioPorVenda);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Grafico");

        mnuGraficoMarca.setText("Marca");
        mnuGraficoMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGraficoMarcaActionPerformed(evt);
            }
        });
        jMenu5.add(mnuGraficoMarca);

        jMenuItem4.setText("Funcionario");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNovoClienteActionPerformed
        NovoClienteForm novoClienteForm = new NovoClienteForm();
        novoClienteForm.setLocation(400, 100);
        pnlPrincipal.add(novoClienteForm);
        novoClienteForm.setVisible(true);
    }//GEN-LAST:event_mnuNovoClienteActionPerformed

    private void mnuNovoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNovoVeiculoActionPerformed
        NovoVeiculoForm novoVeiculoForm = new NovoVeiculoForm();
        novoVeiculoForm.setLocation(400, 100);
        pnlPrincipal.add(novoVeiculoForm);
        novoVeiculoForm.setVisible(true);
    }//GEN-LAST:event_mnuNovoVeiculoActionPerformed

    private void mnuNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNovoFuncionarioActionPerformed
        NovoFuncionarioForm novoFuncionarioForm = new NovoFuncionarioForm();
        novoFuncionarioForm.setLocation(400, 100);
        pnlPrincipal.add(novoFuncionarioForm);
        novoFuncionarioForm.setVisible(true);
    }//GEN-LAST:event_mnuNovoFuncionarioActionPerformed

    private void btnBonificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBonificacaoActionPerformed
        NovoBonificacaoForm novoBonificacaoForm = new NovoBonificacaoForm();
        novoBonificacaoForm.setLocation(400, 100);
        pnlPrincipal.add(novoBonificacaoForm);
        novoBonificacaoForm.setVisible(true);
    }//GEN-LAST:event_btnBonificacaoActionPerformed

    private void mnuListaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListaClienteActionPerformed
        ListaClienteForm listaClienteForm = new ListaClienteForm();
        pnlPrincipal.add(listaClienteForm);
        listaClienteForm.setVisible(true);
    }//GEN-LAST:event_mnuListaClienteActionPerformed

    private void mnuListaVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListaVeiculoActionPerformed
        ListaVeiculoForm listaVeiculoForm = new ListaVeiculoForm();
        pnlPrincipal.add(listaVeiculoForm);
        listaVeiculoForm.setVisible(true);
    }//GEN-LAST:event_mnuListaVeiculoActionPerformed

    private void mnuListaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListaFuncionarioActionPerformed
        ListaFuncionarioForm listaFuncionarioForm = new ListaFuncionarioForm();
        pnlPrincipal.add(listaFuncionarioForm);
        listaFuncionarioForm.setVisible(true);
    }//GEN-LAST:event_mnuListaFuncionarioActionPerformed

    private void mnuNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNovaVendaActionPerformed
        NovaVendaForm novaVendaForm = new NovaVendaForm();
        novaVendaForm.setLocation(400, 100);
        pnlPrincipal.add(novaVendaForm);
        novaVendaForm.setVisible(true);
    }//GEN-LAST:event_mnuNovaVendaActionPerformed

    private void mnuListaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListaVendaActionPerformed
        ListaVendaForm listaVendaForm = new ListaVendaForm();
        pnlPrincipal.add(listaVendaForm);
        listaVendaForm.setVisible(true);
    }//GEN-LAST:event_mnuListaVendaActionPerformed

    private void mnuRelatorioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRelatorioCompraActionPerformed
        try {
            String relatorio = System.getProperty("user.dir") + "/relatorio/relatorioCompra.jasper";

            //Criar a fonte de dados do JasperReport
            JRBeanCollectionDataSource fontedados = new JRBeanCollectionDataSource(new VendaDAO().listaVenda());

            //Gerar o relatorio
            JasperPrint relatorioGerado = JasperFillManager.fillReport(relatorio, null, fontedados);

            //Exibir Relatorio
            JasperViewer jasperViewer = new JasperViewer(relatorioGerado, false);
            jasperViewer.setVisible(true);

        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_mnuRelatorioCompraActionPerformed

    private void mnuFuncionarioPorVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFuncionarioPorVendaActionPerformed
        try {
            String relatorio = System.getProperty("user.dir") + "/relatorio/relatorioFuncionarioVenda.jasper";

            //Criar a fonte de dados do JasperReport
            JRBeanCollectionDataSource fontedados = new JRBeanCollectionDataSource(new FuncionarioDAO().listaFuncionarioPorVenda());

            //Gerar o relatorio
            JasperPrint relatorioGerado = JasperFillManager.fillReport(relatorio, null, fontedados);

            //Exibir Relatorio
            JasperViewer jasperViewer = new JasperViewer(relatorioGerado, false);
            jasperViewer.setVisible(true);

        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_mnuFuncionarioPorVendaActionPerformed

    private void mnuGraficoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGraficoMarcaActionPerformed
        try {
            String relatorio = System.getProperty("user.dir") + "/relatorio/vendaPorMarca.jasper";

            //Criar a fonte de dados do JasperReport
            JRBeanCollectionDataSource fontedados = new JRBeanCollectionDataSource(new VendaDAO().listaVendaPorMarca());

            //Gerar o relatorio
            JasperPrint relatorioGerado = JasperFillManager.fillReport(relatorio, null, fontedados);

            //Exibir Relatorio
            JasperViewer jasperViewer = new JasperViewer(relatorioGerado, false);
            jasperViewer.setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_mnuGraficoMarcaActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnBonificacao;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu mnuBonificacao;
    private javax.swing.JMenuItem mnuFuncionarioPorVenda;
    private javax.swing.JMenuItem mnuGraficoMarca;
    private javax.swing.JMenuItem mnuListaCliente;
    private javax.swing.JMenuItem mnuListaFuncionario;
    private javax.swing.JMenuItem mnuListaVeiculo;
    private javax.swing.JMenuItem mnuListaVenda;
    private javax.swing.JMenuItem mnuNovaVenda;
    private javax.swing.JMenuItem mnuNovoCliente;
    private javax.swing.JMenuItem mnuNovoFuncionario;
    private javax.swing.JMenuItem mnuNovoVeiculo;
    private javax.swing.JMenuItem mnuRelatorioCompra;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
